language: ruby
cache: bundler
sudo: false
env:
  global:
  - secure: BP1+2SDhPKzEIJIkBPMWvxql5SSQ6Br5TwR4VcqwXovRRBMFiu9/mEASmYtZ5+MinOskt7YHgXFM6PT1LRoGsC+E+TghMZWw9j4zaM8OXR7hQAxrvkFMWIcD71ndxMzmXnQnWIi95l9nUaLJ05EYaZy5k79pugLYzMT1ZzIjesM=
before_install:
# Travis CI installs Node v0.10.36 with NPM v1.4.28 which is really old and 
# doesn't support using authentication tokens from ~/.npmrc, so we need to
# install something newer. Using 6.x as the latest LTS release.
- nvm install 6.11
- nvm use 6.11
- rm -f Gemfile.lock
- git clean -fdx
script:
- bundle exec rake spec integration_tests
before_deploy:
- test $TRAVIS_TEST_RESULT = 0
deploy:
- provider: script
  script: "./config.sh"
  on: master
- provider: script
  script: bundle install && bundle exec rake build:and_release_if_updated
  on: master
after_deploy:
- rm -rf pkg
- rm -rf app
notifications:
  email:
    on_success: never
    on_failure: always
